### ISSUE TITLE
Uploader in BetaCast is sucks

### ISSUE THREAD

**Issue by MediaDanyaVideoEditor590** [eviekek/betacast-2009#3]

**Comment by eviekek** [comment]
it was actually one of my first php files i ever made and dates back to
early 2021. I know it sucks but i never took the time to fix it.

**Comment by MediaDanyaVideoEditor590** [comment]
okay sorry

**Comment by MediaDanyaVideoEditor590** [comment]
but can you fix betacast uploader in tomorrow?
idk

**Comment by MediaDanyaVideoEditor590** [comment]
if you don't have time
